name: Nodejs Hello World Action
on: push
jobs:
    Image-Build:
        name: Image Buildings
        runs-on: ubuntu-latest
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
            SSH_KEY_PATH: ${{ github.workspace }}/../private.key

        steps:
            - name: Build and push image
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Print Github context
              run: echo "Printing all Github context ${{ github }}"
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: dinesh4363/id-nodeks:${{ github.sha }}
            - name: Create SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ../private.key
                  sudo chmod 600 ../private.key
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            
            - name: Verify connectivity
              run: ssh -i $SSH_KEY_PATH ubuntu@ec2-18-209-109-235.compute-1.amazonaws.com
