name: Nodejs Hello World Action
on: push

jobs:
    Image-Build:
        name: Image Building
        runs-on: ubuntu-latest
        steps:
            - name: Build and push image
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Print Github context
              run: echo "Printing all Github context ${{ github }}"
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: dinesh4363/id-nodeks:${{ github.sha }}
            

